CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS data (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    domain TEXT UNIQUE,
    msg TEXT,
    token TEXT
);

CREATE TABLE IF NOT EXISTS texts (
    id SERIAL PRIMARY KEY,
    data_id INTEGER NOT NULL REFERENCES data(id) ON DELETE CASCADE,
    name TEXT UNIQUE,
    descr TEXT,
    token TEXT
)
